<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputModFolderName>MapTransformer</OutputModFolderName>
	</PropertyGroup>
	<Import Project="../Targets/Common.targets" />
	<Import Project="../Targets/CommonModdableTimberborn.targets" />
	<ItemGroup>
		<InternalsVisibleTo Include="MapTransformer.Tests" />
	</ItemGroup>
</Project>