<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputModFolderName>ConveyorBelt</OutputModFolderName>
  </PropertyGroup>
  <Import Project="../Targets/Common.targets" />
  <Import Project="../Targets/CommonModdableTimberborn.targets" />
  <Import Project="../Targets/CommonModdableToolGroups.targets" />
  <ItemGroup>
    <ProjectReference Include="..\ConveyorBelt.Algorithm\ConveyorBelt.Algorithm.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="ConveyorBelt.Algorithm" />
    <Using Include="ConveyorBelt.Components" />
    <Using Include="ConveyorBelt.Components.Connections" />
    <Using Include="ConveyorBelt.Components.Visuals" />
    <Using Include="ConveyorBelt.Models" />
    <Using Include="ConveyorBelt.Services" />
    <Using Include="ConveyorBelt.Specs" />
    <Using Include="ConveyorBelt.UI" />
  </ItemGroup>
</Project>
