global using ModdableTimberborn.BuildingSettings;
global using MoreHttpApi.Handlers;
global using MoreHttpApi.Models;
global using MoreHttpApi.Services;
global using MoreHttpApi.Services.JsonConverters;
global using MoreHttpApi.Shared;
global using MoreHttpApi.Shared.Specs;
global using Newtonsoft.Json.Linq;
global using Newtonsoft.Json.Serialization;
global using System.Collections.Specialized;
global using System.Net;
global using CharacterType = MoreHttpApi.Shared.CharacterType;