<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputModFolderName>Fourpillars</OutputModFolderName>
  </PropertyGroup>
  <Import Project="../Targets/Common.targets" />
  <Import Project="../Targets/CommonModdableTimberborn.targets" />
  <ItemGroup>
    <Using Include="ModdableTimberborn.DependencyInjection" />
  </ItemGroup>
</Project>