global using ModdableTimberborn.BonusSystem;
global using ModdableTimberborn.BuildingSettings;
global using ModdableTimberborn.Common;
global using ModdableTimberborn.DependencyInjection;
global using ModdableTimberborn.EntityDescribers;
global using ModdableTimberborn.EntityTracker;
global using ModdableTimberborn.GameModes;
global using ModdableTimberborn.Helpers;
global using ModdableTimberborn.MechanicalSystem;
global using ModdableTimberborn.Registry;
global using ModdableTimberborn.Services;
global using ModdableTimberborn.SoakEffect;
global using ModdableTimberborn.UpdatableEntityStats;
global using System.Linq.Expressions;
global using MechanicalNodeModifierCollection = ModdableTimberborn.Common.ValueModifierCollection<ModdableTimberborn.MechanicalSystem.IModdableMechanicalNodeModifier, ModdableTimberborn.MechanicalSystem.ModdableMechanicalNodeValues, ModdableTimberborn.MechanicalSystem.MechanicalNodeValues>;
global using Priority = Timberborn.PrioritySystem.Priority;
global using ModdableTimberborn.CompatWeatherService;
