global using ModdableTimberborn.Common;
global using ModdableTimberborn.Registry;
global using ModdableTimberborn.Helpers;
global using ModdableTimberborn.MechanicalSystem;

global using MechanicalNodeModifierCollection = ModdableTimberborn.Common.ValueModifierCollection<ModdableTimberborn.MechanicalSystem.IModdableMechanicalNodeModifier, ModdableTimberborn.MechanicalSystem.ModdableMechanicalNodeValues, ModdableTimberborn.MechanicalSystem.MechanicalNodeValues>;