global using BeaverChronicles.Components;
global using BeaverChronicles.Events;
global using BeaverChronicles.Helpers;
global using BeaverChronicles.Models;
global using BeaverChronicles.Services;
global using BeaverChronicles.Services.Conditions;
global using BeaverChronicles.Services.SpecNodes;
global using BeaverChronicles.Specs;
global using BeaverChronicles.Specs.NodeData;
global using BeaverChronicles.UI;
global using ModdableTimberborn.BonusSystem;
global using ModdableTimberborn.CompatWeatherService;
global using ModdableTimberborn.EntityTracker;
global using Newtonsoft.Json.Linq;
global using Random = UnityEngine.Random;
