global using BeaverChronicles.Components;
global using BeaverChronicles.Events;
global using BeaverChronicles.Helpers;
global using BeaverChronicles.Models;
global using BeaverChronicles.Services;
global using BeaverChronicles.UI;
global using ModdableTimberborn.BonusSystem;
global using ModdableTimberborn.CompatWeatherService;
global using ModdableTimberborn.EntityTracker;
global using Random = UnityEngine.Random;
