<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputModFolderName>PowerOverdrive</OutputModFolderName>
	</PropertyGroup>

	<Import Project="../Targets/Common.targets" />
	<Import Project="../Targets/CommonModdableTimberborn.targets" />
	<Import Project="../Targets/CommonGlobalInventory.targets" />

	<ItemGroup>
		<Using Include="PowerOverdrive.Components" />
		<Using Include="PowerOverdrive.Services" />
		<Using Include="PowerOverdrive.Specs" />
		<Using Include="PowerOverdrive.UI" />
		<Using Include="ModdableTimberborn.MechanicalSystem" />
	</ItemGroup>

</Project>
