<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputModFolderName>BeaverChroniclesWaterfallEventPack</OutputModFolderName>
	</PropertyGroup>

	<Import Project="../Targets/CommonJson.targets" />

	<PropertyGroup>
		<!-- Source files sit at the project root, so copy into the game version folder. -->
		<ModFolder>$(GameModsFolder)$(OutputModFolderName)\version-1.1\</ModFolder>
	</PropertyGroup>
</Project>
