<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<Import Project="./CommonDistroStorage.targets" />
	
	<PropertyGroup>
		<BuildingRenovationsPath>$(GameModsFolder)BuildingRenovations\$(TimberbornVersion)\**\*.dll</BuildingRenovationsPath>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="BuildingRenovations" />
		<Using Include="BuildingRenovations.Components" />
		<Using Include="BuildingRenovations.Renovations" />
		<Using Include="BuildingRenovations.Services" />
		<Using Include="BuildingRenovations.Specs" />
		<Using Include="BuildingRenovations.Helpers" />

		<Reference Include="$(BuildingRenovationsPath)" Private="False" />
	</ItemGroup>

</Project>